'use client';

import { useState, useEffect, useRef } from 'react';
import { useWallet } from '@txnlab/use-wallet-react';
import { ProofCardModal } from './ProofCardModal.js';

const API_URL = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3010';
const WS_URL = process.env['NEXT_PUBLIC_WS_URL'] ?? 'ws://localhost:3010/ws';
const MIN_BET_MICROALGO = 500_000n;
const MAX_BET_MICROALGO = 500_000n;

type FlipState = 'idle' | 'submitting' | 'pending' | 'resolved';

interface ResolvedResult {
  outcome: 'heads' | 'tails';
  netPayoutMicroalgo: bigint;
  vrfRound: bigint;
  txnId: string;
}

/**
 * CoinflipGame -- the main client component for the coin flip game.
 *
 * Architecture:
 *   1. User connects wallet via WalletProvider (use-wallet-react 4.6.0)
 *   2. User clicks Flip -- we construct the group txn via @fairground/sdk client
 *      (generated by algokit-client-generator) and call signTransactions()
 *   3. After flip() confirms on-chain, POST to /games/coinflip/bets to register
 *   4. WS subscription receives bet:resolved event when keeper settles it
 *   5. ProofCardModal shows the VRF proof PNG
 *
 * TODO: Replace placeholder txn submission with real @fairground/sdk generated client
 *       after running: algokit generate client packages/contracts/artifacts/ --output packages/sdk/src/clients/
 */
export function CoinflipGame(): React.ReactElement {
  const { activeAddress, signTransactions } = useWallet();
  const [flipState, setFlipState] = useState<FlipState>('idle');
  const [vrfRound, setVrfRound] = useState<bigint | null>(null);
  const [result, setResult] = useState<ResolvedResult | null>(null);
  const [showProof, setShowProof] = useState(false);
  const [betId, setBetId] = useState<string | null>(null);
  const wsRef = useRef<WebSocket | null>(null);

  // Subscribe to WS for bet resolution events
  useEffect(() => {
    if (!betId) return;

    const ws = new WebSocket(WS_URL);
    wsRef.current = ws;

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data as string) as {
          type: string;
          betId?: string;
          outcome?: string;
          netPayoutMicroalgo?: string;
          vrfRound?: string;
          proofCardUrl?: string | null;
        };

        if (data.type === 'bet:resolved' && data.betId === betId) {
          setResult({
            outcome: (data.outcome ?? 'tails') as 'heads' | 'tails',
            netPayoutMicroalgo: BigInt(data.netPayoutMicroalgo ?? '0'),
            vrfRound: BigInt(data.vrfRound ?? '0'),
            txnId: betId,  // using betId as placeholder; real txnId from resolve event
          });
          setFlipState('resolved');
          setShowProof(true);
          ws.close();
        }
      } catch {
        // Malformed WS message -- ignore
      }
    };

    ws.onerror = (err) => console.error('[CoinflipGame] WS error:', err);

    return () => ws.close();
  }, [betId]);

  // Countdown timer while waiting for VRF
  const [roundsRemaining, setRoundsRemaining] = useState<number>(8);
  useEffect(() => {
    if (flipState !== 'pending' || !vrfRound) return;
    const interval = setInterval(() => {
      setRoundsRemaining((r) => Math.max(0, r - 1));
    }, 2800);  // ~2.8s per Algorand block
    return () => clearInterval(interval);
  }, [flipState, vrfRound]);

  const handleFlip = async (): Promise<void> => {
    if (!activeAddress) return;
    setFlipState('submitting');

    try {
      // TODO: Replace with generated SDK client call:
      // import { CoinflipContractClient } from '@fairground/sdk';
      // const client = new CoinflipContractClient({ id: BigInt(NEXT_PUBLIC_COINFLIP_APP_ID), algod });
      // const result = await client.flip({ salt_hash: saltHash, referrer: zeroAddress }, { signer });
      // For now, show a placeholder error until client is generated.
      throw new Error('Flip not yet implemented -- run algokit generate client to generate SDK client');
    } catch (err) {
      console.error('[CoinflipGame] flip error:', err);
      setFlipState('idle');
      alert(err instanceof Error ? err.message : 'Unknown error');
    }
  };

  if (!activeAddress) {
    return (
      <div className="flex flex-col items-center gap-6 py-16">
        <p className="text-lg text-amber-400/70">Connect your wallet to play</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center gap-8 py-12">
      {/* Coin */}
      <div
        className="flex items-center justify-center w-40 h-40 rounded-full border-4 border-amber-500/60 text-6xl"
        style={{
          background: flipState === 'resolved' && result
            ? result.outcome === 'heads' ? 'rgba(62,184,106,0.15)' : 'rgba(196,48,48,0.15)'
            : 'rgba(212,150,58,0.08)',
          transition: 'background 0.5s ease',
        }}
      >
        {flipState === 'pending' ? '🔄' : flipState === 'resolved' && result
          ? result.outcome === 'heads' ? '✅' : '❌'
          : '🪙'}
      </div>

      {/* Status */}
      {flipState === 'pending' && vrfRound && (
        <div className="text-center">
          <p className="text-amber-400/70 text-sm">Waiting for VRF round #{vrfRound.toString()}</p>
          <p className="text-amber-400 text-2xl font-mono font-bold mt-1">
            ~{roundsRemaining * 3}s
          </p>
        </div>
      )}

      {flipState === 'resolved' && result && (
        <div className="text-center">
          <p className={`text-4xl font-bold ${result.outcome === 'heads' ? 'text-green-400' : 'text-red-400'}`}>
            {result.outcome === 'heads' ? 'HEADS -- YOU WIN!' : 'TAILS -- BETTER LUCK NEXT TIME'}
          </p>
          {result.outcome === 'heads' && (
            <p className="text-amber-400 mt-2">
              +{(Number(result.netPayoutMicroalgo) / 1_000_000).toFixed(4)} ALGO
            </p>
          )}
        </div>
      )}

      {/* Bet display */}
      <div className="text-center text-sm text-amber-400/50">
        Bet: {Number(MIN_BET_MICROALGO) / 1_000_000} ALGO fixed (v1)
      </div>

      {/* Action button */}
      {flipState === 'idle' || flipState === 'resolved' ? (
        <button
          onClick={() => { void handleFlip(); }}
          disabled={flipState === 'submitting'}
          className="px-8 py-4 text-lg font-bold rounded-lg bg-amber-500 text-stone-950 hover:bg-amber-400 transition-colors disabled:opacity-50"
        >
          {flipState === 'resolved' ? 'Flip Again' : 'Flip (0.5 ALGO)'}
        </button>
      ) : null}

      {/* Proof card modal */}
      {showProof && result && betId && (
        <ProofCardModal
          txnId={betId}
          outcome={result.outcome}
          netPayoutMicroalgo={result.netPayoutMicroalgo}
          vrfRound={result.vrfRound}
          onClose={() => setShowProof(false)}
        />
      )}
    </div>
  );
}
