'use client';

import { useState } from 'react';

interface Props {
  txnId: string;
  outcome: 'heads' | 'tails' | 'jackpot';
  netPayoutMicroalgo: bigint;
  vrfRound: bigint;
  onClose: () => void;
}

const API_URL = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3010';

/**
 * ProofCardModal -- share your VRF proof card after a flip resolves.
 *
 * Fetches the PNG from /proof/:txnId (generated by @fairground/proof-card).
 * Provides a Twitter/X share-intent URL.
 *
 * Share-intent URL template:
 *   https://twitter.com/intent/tweet
 *     ?text=I+just+flipped+heads+on+@fairground+🪙+Provably+fair+VRF+on+Algorand
 *     &url=https://api.fairground.xyz/proof/{txnId}
 */
export function ProofCardModal({ txnId, outcome, netPayoutMicroalgo, vrfRound, onClose }: Props): React.ReactElement {
  const [imageLoaded, setImageLoaded] = useState(false);

  const proofUrl = `${API_URL}/proof/${txnId}`;
  const algoAmount = (Number(netPayoutMicroalgo) / 1_000_000).toFixed(4);

  const tweetText =
    outcome === 'tails'
      ? `Just flipped TAILS on @fairground 🪙 Better luck next time. VRF round #${vrfRound}`
      : `Just flipped HEADS on @fairground 🪙 Won ${algoAmount} ALGO! VRF round #${vrfRound} — provably fair on Algorand`;

  const shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}&url=${encodeURIComponent(proofUrl)}`;

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: '#1a100a',
          border: '1px solid #3d2210',
          borderRadius: '12px',
          padding: '24px',
          maxWidth: '680px',
          width: '90vw',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ marginBottom: '16px', fontSize: '18px', fontWeight: 700, color: '#f0e8d8' }}>
          VRF Proof of Fairness
        </div>

        {/* Proof card image */}
        <div style={{ marginBottom: '16px', borderRadius: '8px', overflow: 'hidden' }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={proofUrl}
            alt="VRF proof card"
            style={{ width: '100%', display: imageLoaded ? 'block' : 'none' }}
            onLoad={() => setImageLoaded(true)}
          />
          {!imageLoaded && (
            <div style={{ height: '200px', background: '#241407', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#a0856a' }}>
              Loading proof...
            </div>
          )}
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
          <a
            href={shareUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              background: '#d4963a',
              color: '#110c08',
              padding: '10px 20px',
              borderRadius: '6px',
              fontWeight: 700,
              textDecoration: 'none',
              fontSize: '15px',
            }}
          >
            Share on X
          </a>
          <a
            href={proofUrl}
            download={`proof-${txnId.slice(0, 8)}.png`}
            style={{
              background: '#2e1a0e',
              color: '#d4963a',
              padding: '10px 20px',
              borderRadius: '6px',
              fontWeight: 700,
              textDecoration: 'none',
              fontSize: '15px',
              border: '1px solid #3d2210',
            }}
          >
            Download PNG
          </a>
          <button
            onClick={onClose}
            style={{
              marginLeft: 'auto',
              background: 'transparent',
              color: '#a0856a',
              border: '1px solid #3d2210',
              padding: '10px 16px',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '15px',
            }}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
