// @fairground/sdk -- bridge between Puya contracts and TypeScript apps.
//
// src/clients/ is auto-generated by algokit-client-generator@6.0.1
// from packages/contracts/artifacts/*.arc56.json.
// NEVER edit generated files by hand -- regenerate via:
//   algokit generate client packages/contracts/artifacts/ --output packages/sdk/src/clients/

// Re-export VRF beacon utilities
export * from './vrf/beacon.js';

// Generated clients (populated after: algokit generate client ...)
// export * from './clients/CoinflipContractClient.js';
// export * from './clients/HouseTreasuryClient.js';
// export * from './clients/LeaderboardContractClient.js';
