// @fairground/sdk -- bridge between Puya contracts and TypeScript apps.
//
// src/clients/ is auto-generated by algokit-client-generator@6.0.1
// from packages/contracts/artifacts/*.arc56.json.
// NEVER edit generated files by hand -- regenerate via:
//   algokit generate client packages/contracts/artifacts/ --output packages/sdk/src/clients/

// Re-export VRF beacon utilities
export * from './vrf/beacon.js';

// AlgorandClient factory
export * from './algorand-client.js';

// Generated ARC-56 clients (regenerate via `make contracts-generate`).
// Named exports only -- every generated client re-exports identical generic
// helpers (APP_SPEC, MethodArgs, ...) so `export *` would collide.
export { CoinflipContractClient, CoinflipContractFactory } from './clients/CoinflipClient.js';
export { HouseTreasuryClient, HouseTreasuryFactory } from './clients/HouseTreasuryClient.js';
export {
  LeaderboardContractClient,
  LeaderboardContractFactory,
} from './clients/LeaderboardClient.js';
export { FairJackpotClient, FairJackpotFactory } from './clients/FairJackpotClient.js';
