/**
 * Run Drizzle ORM migrations at keeper startup.
 *
 * Called before the main polling loop so the schema is always up to date
 * before the keeper begins processing sessions. Safe to call in both the
 * primary and standby instance — Drizzle's migrate() is idempotent and
 * uses Postgres advisory locks internally.
 *
 * The migrations live in packages/db/drizzle/ (generated by drizzle-kit).
 * The keeper reads them from the published dist if running via `node dist/`,
 * or from the source path when running via `tsx src/` in development.
 */

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import pino from 'pino';

const logger = pino({ level: 'info' });

// drizzle/migrations directory is relative to the packages/db package root.
// When running as an ESM module from the monorepo, __dirname points into
// packages/keeper/src (tsx) or packages/keeper/dist (node). Both are two
// levels below the repo root packages/ directory.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// packages/db/drizzle is always at ../../db/drizzle relative to keeper/src|dist
const MIGRATIONS_DIR = join(__dirname, '../../db/drizzle');

export async function runMigrations(databaseUrl: string): Promise<void> {
  const pool = new Pool({ connectionString: databaseUrl, max: 1 });

  try {
    const db = drizzle(pool);
    logger.info({ migrationsDir: MIGRATIONS_DIR }, 'keeper: running migrations');
    await migrate(db, { migrationsFolder: MIGRATIONS_DIR });
    logger.info('keeper: migrations complete');
  } finally {
    await pool.end();
  }
}
