"""
Deploy configuration for Fairground smart contracts.

AlgoKit reads this file via the `algokit deploy` command.
Each function is responsible for deploying (or updating) one contract.

Deploy order is enforced by the dependency graph:
    1. HouseTreasury  — no external deps
    2. LeaderboardContract — depends on nothing at deploy time
    3. CoinflipContract — depends on HouseTreasury + optionally Leaderboard

After deploying:
    - Register CoinflipContract in HouseTreasury (register_game).
    - Register CoinflipContract in LeaderboardContract (register_caller).
    - Set leaderboard_app_id on CoinflipContract (set_leaderboard_app_id).
    - Fund HouseTreasury with at least 2,000 ALGO before public announcement.

Environment variables required:
    ADMIN_MNEMONIC            — deployer and admin wallet mnemonic
    ALGOD_SERVER              — algod endpoint (default: http://localhost)
    ALGOD_PORT                — algod port (default: 4001)
    ALGOD_TOKEN               — algod token (default: aaaaaaa...a for LocalNet)
    MIN_BET_MICROALGO         — minimum bet (default: 500000 = 0.5 ALGO)
    MAX_BET_MICROALGO         — maximum bet (default: 500000 = 0.5 ALGO)

Usage:
    algokit deploy  # uses .algokit.toml + this file
    # or directly:
    python smart_contracts/deploy_config.py
"""

import os
import logging

# TODO: import generated TypeScript clients from packages/sdk/src/clients/ via
# the Python equivalents generated by `algokit generate client --language python`.
# For now, use algokit_utils.ApplicationClient as a placeholder.

try:
    from algokit_utils import ApplicationClient, AlgorandClient
except ImportError:
    # algokit_utils is installed by AlgoKit; this guard prevents import errors
    # when linting without the full virtualenv active.
    ApplicationClient = None  # type: ignore[assignment,misc]
    AlgorandClient = None     # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)


def deploy_house_treasury(algorand: "AlgorandClient", admin_address: str) -> str:
    """
    Deploy (or update) HouseTreasury.

    Returns the deployed app ID as a string for use in downstream deploys.

    TODO: replace placeholder with generated HouseTreasuryClient from
    packages/sdk/src/clients/HouseTreasuryClient.ts (Python equivalent).
    """
    logger.info("Deploying HouseTreasury...")

    # TODO: load compiled artifact from artifacts/house_treasury.arc56.json
    # client = HouseTreasuryClient(algorand)
    # result = client.create(admin=admin_address)
    # logger.info(f"HouseTreasury deployed at app_id={result.app_id}")
    # return str(result.app_id)

    raise NotImplementedError(
        "Deploy HouseTreasury: implement after running 'algokit compile python smart_contracts/'"
        " and regenerating TypeScript clients via 'algokit generate client'."
    )


def deploy_leaderboard(algorand: "AlgorandClient", admin_address: str) -> str:
    """
    Deploy (or update) LeaderboardContract.

    Returns the deployed app ID as a string.

    TODO: implement after HouseTreasury deploy is confirmed working.
    """
    logger.info("Deploying LeaderboardContract...")

    raise NotImplementedError(
        "Deploy LeaderboardContract: implement after HouseTreasury is deployed."
    )


def deploy_coinflip(
    algorand: "AlgorandClient",
    admin_address: str,
    treasury_app_id: int,
    beacon_app_id: int,
    leaderboard_app_id: int,
) -> str:
    """
    Deploy (or update) CoinflipContract.

    Args:
        treasury_app_id:    Deployed HouseTreasury app ID.
        beacon_app_id:      VRF beacon app ID (947957720 mainnet).
        leaderboard_app_id: Deployed LeaderboardContract app ID (0 = disabled).

    Returns the deployed app ID as a string.

    TODO: implement using generated CoinflipClient.
    """
    logger.info("Deploying CoinflipContract...")

    min_bet = int(os.getenv("MIN_BET_MICROALGO", "500000"))
    max_bet = int(os.getenv("MAX_BET_MICROALGO", "500000"))

    # TODO: CoinflipClient(algorand).create(...)
    # After deploy, call:
    #   treasury_client.register_game(coinflip_app_id)
    #   leaderboard_client.register_caller(coinflip_app_id)
    #   coinflip_client.set_leaderboard_app_id(leaderboard_app_id)

    raise NotImplementedError(
        "Deploy CoinflipContract: implement using generated CoinflipClient."
    )

    # Suppress unused variable warnings until implemented.
    _ = min_bet, max_bet, treasury_app_id, beacon_app_id, leaderboard_app_id


def main() -> None:
    """Full deploy sequence. Run via: python smart_contracts/deploy_config.py"""
    logging.basicConfig(level=logging.INFO)

    # TODO: load AlgorandClient from env vars.
    # algorand = AlgorandClient.from_environment()
    # admin = algorand.account.from_mnemonic(os.environ["ADMIN_MNEMONIC"])

    # MAINNET_BEACON_APP_ID = 947957720
    # treasury_app_id = deploy_house_treasury(algorand, admin.address)
    # leaderboard_app_id = deploy_leaderboard(algorand, admin.address)
    # coinflip_app_id = deploy_coinflip(
    #     algorand,
    #     admin.address,
    #     treasury_app_id=int(treasury_app_id),
    #     beacon_app_id=MAINNET_BEACON_APP_ID,
    #     leaderboard_app_id=int(leaderboard_app_id),
    # )
    # logger.info(f"Deploy complete. treasury={treasury_app_id} coinflip={coinflip_app_id}")

    raise NotImplementedError("main() deploy not yet implemented — see TODOs above.")


if __name__ == "__main__":
    main()
